# Generated by Django 5.0.1 on 2024-01-06 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=63, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('background', models.ImageField(blank=True, upload_to='category/background')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPhoto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_photo/image')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('tin', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('description', models.CharField(blank=True, max_length=63)),
                ('cost', models.FloatField(default=False)),
                ('preview', models.ImageField(blank=True, upload_to='product/preview')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='category_id')),
                ('photos', models.ManyToManyField(blank=True, to='products.customphoto')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seller', verbose_name='seller_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=63, unique=True)),
                ('value', models.CharField(max_length=63, unique=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product_id')),
            ],
        ),
    ]
