# Generated by Django 5.0.1 on 2024-01-14 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('accompanying', models.TextField(max_length=1024)),
                ('salary_low', models.FloatField(blank=True, null=True)),
                ('salary_top', models.FloatField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='ticket/job/')),
                ('resume_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=2048)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_order_customer_id', to='products.customer')),
                ('files', models.ManyToManyField(blank=True, related_name='order_ticket_file', to='files.file')),
            ],
        ),
    ]
