# Generated by Django 5.0.1 on 2024-01-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
