# Generated by Django 5.0.1 on 2024-01-14 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=2048)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=512)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='service/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=512)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
            ],
        ),
    ]
