name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Installing libs
        run: npm i 

      - name: Linting
        run: npm run lint

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Preparing frontend image
        run: docker build -t ${{ github.event.repository.name }}-frontend -f ./Dockerfile .

      - name: Tagging frontend image
        run: docker image tag ${{ github.event.repository.name }} ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-frontend:latest

      - name: Pushing frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-frontend:latest


  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Preparing backend image
        run: docker build -t ${{ github.event.repository.name }}-backend -f ./Dockerfile .

      - name: Tagging backend image
        run: docker image tag ${{ github.event.repository.name }} ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-backend:latest

      - name: Pushing backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-backend:latest